### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by masterfamp** [cristhoper/LibreQnQ#1]
Cristhoper, 
 
 Este código pertenece a Emulator. Por favor baja este código para evitar inconvenientes con la empresa holding dueña Emulator y su correspondiente propiedad intelectual.

 This source code is property of Emulator. Please, remove this code from this repository to prevent problems with Emulator's intelectual property owners.

**Comment by cristhoper** [comment]
#c4844c5ba0ee48f52b2616c17dd0a941cd185dfb rebase.
